# Basket option implementation with Bachelier model CV

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import numpy as np
import pyfeng as pf

#import option_models as opt
from option_models import basket

In [3]:
# A trivial test case 1: 
# one asset have 100% weight (the others zero)
# the case should be equivalent to the BSM or Normal model price

spot = np.ones(4) * 100
vol = np.ones(4) * 0.4
weights = np.array([1, 0, 0, 0])
divr = np.zeros(4)
intr = 0
cor_m = 0.5*np.identity(4) + 0.5
texp = 5
strike = 120

In [4]:
print(spot,'\n',vol,'\n')

[100. 100. 100. 100.] 
 [0.4 0.4 0.4 0.4] 



In [5]:
# n_assets = spot.size
# print(n_assets)
# for k in range(1,n_assets+1):
#     print(k)

In [6]:
# a=spot
# b=spot
# prices= np.stack((a,a,a))
# print(np.vstack((prices,a)))

In [7]:
# prices = np.ones((4,4))
# prices
# np.exp(5+spot @ prices)

In [8]:
# for k in range(0,4):
#     prices[k] = spot
# print(prices)

In [9]:
# cor_m

In [10]:
print(weights)

np.random.seed(123456)
price_basket = basket.basket_price_mc(strike, spot, vol*spot, weights, texp, cor_m, bsm=False)
print(price_basket)


[1 0 0 0]
[[141.95867967  74.69993335 -34.9742958  ... -88.908807     0.86849404
   86.87805409]
 [ 90.21743281 116.87720924 -32.3320603  ... 207.91513884  30.09914102
  -12.61904954]
 [119.40698288 198.73183879 -70.00353151 ...  39.99401176 113.40496662
  -79.27018149]
 [ 96.22460758 124.14605188  96.22155167 ...  96.52234547  87.88424219
    6.75441909]]
26.570984651213593


In [11]:
# Compare the price to normal model formula

norm1 = pf.Norm(sigma=40)
price_norm = norm1.price(strike, spot[0], texp, cp=1)
print(price_basket, price_norm)

26.570984651213593 26.570845957870503


In [12]:
# A trivial test case 2
# all assets almost perfectly correlated:
# the case should be equivalent to the BSM or Normal model price

spot = np.ones(4) * 100
vol = np.ones(4) * 0.4
weights = np.ones(4) * 0.25
divr = np.zeros(4)
intr = 0
cor_m = 0.0001*np.identity(4) + 0.9999*np.ones((4,4))
texp = 5
strike = 120

print( cor_m )

np.random.seed(123456)
price_basket = basket.basket_price_mc(strike, spot, vol*spot, weights, texp, cor_m, bsm=False)
print(price_basket, price_norm)

[[1.     0.9999 0.9999 0.9999]
 [0.9999 1.     0.9999 0.9999]
 [0.9999 0.9999 1.     0.9999]
 [0.9999 0.9999 0.9999 1.    ]]
[[141.95867967  74.69993335 -34.9742958  ... -88.908807     0.86849404
   86.87805409]
 [141.45215652  75.18462915 -36.01968489 ... -85.58531795   0.5463446
   85.14748845]
 [141.83355581  76.46661338 -36.70372624 ... -87.73281701   1.7586118
   83.95314009]
 [141.50324202  75.47412413 -34.35306963 ... -86.93867165   1.45242241
   85.0785222 ]]
26.57211110181949 26.570845957870503


In [13]:
# A full test set for basket option with exact price

spot = np.ones(4) * 100
vol = np.ones(4) * 0.4
weights = np.ones(4) * 0.25
divr = np.zeros(4)
intr = 0
cor_m = 0.5*np.identity(4) + 0.5
texp = 5
strike = 100
price_exact = 28.0073695

In [14]:
weights, cor_m
cor_m[3,3]

1.0

In [15]:
price_basket = basket.basket_price_mc(strike, spot, vol*spot, weights, texp, cor_m, bsm=False)
print(price_basket, price_exact)

[[ -1.12398157 -42.05767661 222.55759998 ... 206.93880058 111.72219117
   20.19372145]
 [ 74.38073019 131.92344844 345.67930134 ...  25.52021138 134.28788645
  -39.62816339]
 [-68.60688631  15.1177975  206.20705483 ... 190.20382521  53.57504896
   61.7444636 ]
 [-62.9103599   65.31361086 124.3866139  ...  61.35433913 -13.14304127
  -57.7489216 ]]
28.22782882893394 28.0073695


# [To Do] Basket option implementation based on BSM model
## Write the similar test for BSM

In [16]:
price_basket = basket.basket_price_mc(strike, spot, vol, weights, texp, cor_m, bsm=True)
print(price_basket)

[[ 3.65912281  6.37095322  6.60300825 ...  9.71283979  3.77139746
  12.91671071]
 [ 3.90794189  3.17770485  5.61385093 ...  2.73235188  3.91249178
  75.69408243]
 [ 8.26330313  3.01761654  5.26103001 ...  5.82777775  6.92016766
  23.23957419]
 [ 4.55505916  4.15963215  8.20493724 ...  6.27341321  2.21940795
  17.57238905]]
0.011505082295929002


In [17]:
# A trivial test case 1: 
# one asset have 100% weight (the others zero)
# the case should be equivalent to the BSM or Normal model price

spot = np.ones(4) * 100
vol = np.ones(4) * 0.4
weights = np.array([1, 0, 0, 0])
divr = np.zeros(4)
intr = 0
cor_m = 0.5*np.identity(4) + 0.5
texp = 5
strike = 120

print(weights)

np.random.seed(123456)
price_basket = basket.basket_price_mc(strike, spot, vol, weights, texp, cor_m, bsm=True)

[1 0 0 0]
[[12.48786013  6.37363225  2.12852069 ...  1.2412043   3.04607881
   7.19906191]
 [ 7.4435249   9.71763502  2.18551081 ... 24.15089826  4.08026361
   2.66173906]
 [ 9.9666051  22.03183767  1.49950473 ...  4.50465048  9.38600596
   1.36679471]
 [ 7.90437388 10.4503002   7.90413233 ...  7.92794326  7.27186366
   3.23075022]]


In [18]:
bsm1 = pf.Bsm(sigma=vol[0])
price_bsm = bsm1.price(strike, spot[0], texp, cp=1)
print(price_basket, price_bsm)

0.0426837950448571 28.713486748445934


# Spread option implementation based on normal model

In [19]:
# A full test set for spread option

spot = np.array([100, 96])
vol = np.array([0.2, 0.1])
weights = np.array([1, -1])
divr = np.array([1, 1])*0.05
intr = 0.1
cor = 0.5
cor_m = np.array([[1, cor], [cor, 1]])
texp = 1
strike = 0
price_exact = 8.5132252

In [20]:
# MC price based on normal model
# make sure that the prices are similar

np.random.seed(123456)
price_spread = basket.basket_price_mc(strike, spot, vol*spot, weights, texp, cor_m, intr=intr, divr=divr, bsm=False)
print(price_spread, price_exact)

[[114.50935564  99.46984275  74.94593957 ...  62.88581624  82.96063103
  102.19295333]
 [ 99.87204996 102.73347743  86.7186581  ... 112.50469339  93.41947778
   88.83448044]]
8.317680907159142 8.5132252


# Spread option implementation based on BSM model

In [21]:
# Once the implementation is finished the BSM model price should also work
price_spread = basket.basket_price_mc(
    strike, spot, vol*spot, weights, texp, cor_m, intr=intr, divr=divr, bsm=True)
price_spread

[[6.87270231e+02 7.60868052e+13 1.52209331e-08 ... 7.56313134e-03
  1.25972540e+10 2.93678478e-15]
 [1.52539903e+01 5.82591014e+04 7.36400838e+04 ... 2.93088350e+02
  1.39902676e+05 9.96183760e-04]]


3.185617880930005e+35

In [22]:
# You also test Kirk's approximation
kirk = pf.BsmSpreadKirk(vol, cor=cor, divr=divr, intr=intr)
price_kirk = kirk.price(strike, spot, texp)
print(price_kirk, price_spread)

8.513225229545505 3.185617880930005e+35


# [To Do] Complete the implementation of basket_price_norm_analytic
# Compare the MC stdev of BSM basket prices from with and without CV

In [23]:
# The basket option example from above
spot = np.ones(4) * 100
vol = np.ones(4) * 0.4
weights = np.array([1, 1, 1, 1])/4
divr = np.zeros(4)
intr = 0
cor_m = 0.5*np.identity(4) + 0.5
texp = 5
strike = 120

In [24]:
### Make sure that the analytic normal price is correctly implemented
basket.basket_price_norm_analytic(strike, spot, vol*spot, weights, texp, cor_m, intr=intr, divr=divr)

array([1.53227938e-07, 1.53227938e-07, 1.53227938e-07, 1.53227938e-07])

In [25]:
# Run below about 100 times and get the mean and stdev

### Returns 2 prices, without CV and with CV 
price_basket = basket.basket_price_mc_cv(strike, spot, vol, weights, texp, cor_m)fss

[[ 2.98598707  1.98296544 27.95919668 ...  9.05774387  1.82936227
  14.77298885]
 [ 1.21013826  0.90967536 16.51142016 ...  5.36094529  6.82324956
  20.64663716]
 [ 2.25448709 17.71324308 11.02912768 ...  9.46998011  1.87134809
  49.73910551]
 [ 5.381938    4.31446911 15.68002791 ... 22.41280401  6.39331691
  25.29521091]]
[[ 5.35940458  4.44523174  1.60264967 ...  7.77464867  6.77775814
  22.84506097]
 [10.70017069 18.55499618  2.49314907 ... 24.95415871  9.74818097
  25.4086022 ]
 [ 5.66252017  5.79156444  7.86404811 ...  5.5716996   8.01619887
  13.20325577]
 [ 3.09493544  7.92147263  6.54822316 ...  3.86495618  4.48945737
   6.42867372]]


C:\Users\wishe\courses\ASP\HW2\option_models\basket.py:54: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  return np.array([price1, price1 - (price2 - price3)])


In [26]:
print(price_basket)

[0.01582393727641322
 array([0.01025937, 0.01025937, 0.01025937, 0.01025937])]


In [ ]:
a= np.ones(2)*2
b= np.ones(2)*3

In [ ]:
a*b

In [ ]:
np.sqrt(9)